import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { emphasize, fade, darken, lighten } from '@material-ui/core/styles/colorManipulator';

import clsx from 'clsx';

import Paper from '@material-ui/core/Paper';
import Grid from '@material-ui/core/Grid';
import Box from '@material-ui/core/Box';
import Container from '@material-ui/core/Container';
import Typography from '@material-ui/core/Typography';

import meeting from './../images/meeting.jpg';


const useStyles = makeStyles((theme) => ({
  section: {
    width: "100%",
  },
  contentBox: {
    maxWidth: theme.breakpoints.values['md'],
    paddingTop: theme.spacing(7),
    paddingBottom: theme.spacing(8),
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
    [theme.breakpoints.up('lg')]: {
      maxWidth: theme.breakpoints.values['lg'] / 2,
      maxHeight: 525,
      paddingTop: theme.spacing(7),
      paddingBottom: theme.spacing(16),
      marginRight: 0,
      textAlign: 'left',
    }
  },
  img: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    objectFit: 'cover',
    height: 525,
    width: '100%'
  },
    title: {
     [theme.breakpoints.down('xs')]: {
       fontSize: "26px",
     },
     [theme.breakpoints.up('sm')]: {
       fontSize: "32px",
     },
     [theme.breakpoints.up('md')]: {
       fontSize: "42px",
     },
     [theme.breakpoints.up('lg')]: {
       fontSize: "46px",
     }
    },
     text: {
     [theme.breakpoints.down('xs')]: {
       fontSize: "15px",
     },
     [theme.breakpoints.up('sm')]: {
       fontSize: "18px",
     },
     [theme.breakpoints.up('md')]: {
       fontSize: "20px",
     },
     [theme.breakpoints.up('lg')]: {
       fontSize: "24px",
     }
    }
}
));

export default function Component(props) {
  const classes = useStyles();

  return (
<Paper>
<section className={classes.section}>
  <Grid container>
    <Grid item xs={12} lg={6}>
      <Box className={classes.contentBox}>
        <Container>
          <Typography variant="h3" component="h2" className={classes.title} gutterBottom={true}>our why</Typography>
          <Typography variant="h5" className={classes.text} paragraph={true}>Cost benefit analysis is an evaluation service that compares the costs of a company's product to the financial benefits that will be gained in the creation. All expenditures such as costs to develop, market, and support a product are evaluated against the revenue generated by customers or partnerships to determine if a product upcoming product is a cost-effective opportunity. We generate the analysis, you make the decision. Begin your cost benefit analysis today.</Typography>
        </Container>
      </Box>
    </Grid>
    <Grid item xs={12} lg={6}>
      <Box position="relative" height={512}>
        <img className={classes.img} src={meeting} alt="" />
      </Box>
    </Grid>
  </Grid>
</section>
</Paper>
  );
}